### ISSUE TITLE
Project dead?  Recently lots of issues with no compatible version found

### ISSUE THREAD

**Issue by MichaelJCole** [local-npm/local-npm#169]
## Detailed Description
Hey, this is a cool project, but it looks dead.  Recently I'm having a bunch of issues like this one:
```
wget -qO /dev/null 'http://127.0.0.1:5080/_browse/' && npm set registry http://127.0.0.1:5080 && echo '----> local-npm found <----'
# Npm install if not already.
`which hexo > /dev/null` || npm install -g hexo-cli
```
outputs:
```
----> local-npm found <----
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: supports-color@^5.3.0 (node_modules/chalk/node_modules/supports-color):
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: No compatible version found: supports-color@^5.3.0
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: Valid install targets:
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: 5.2.0, 5.1.0, 5.0.1, 5.0.0, 4.5.0, 4.4.0, 4.3.0, 4.2.1, 4.2.0, 4.1.0, 4.0.0, 3.2.3, 3.2.2, 3.2.1, 3.2.0, 3.1.2, 3.1.1, 3.1.0, 3.0.1, 3.0.0, 2.0.0, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.0, 0.2.0
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: 
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/home/michael/.nvm/versions/node/v6.13.1/bin/node" "/home/michael/.nvm/versions/node/v6.13.1/bin/npm" "install"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: ansi-styles@^3.2.1
npm ERR! notarget Valid install targets:
npm ERR! notarget 3.2.0, 3.1.0, 3.0.0, 2.2.1, 2.1.0, 2.0.1, 2.0.0, 1.1.0, 1.0.0, 0.2.0, 0.1.2, 0.1.1, 0.1.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'chalk'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/michael/scm/site/www/npm-debug.log
```
## Context
`local-npm` isn't caching correctly, and it's bumming me out :-) 

## Workaround
```
npm set registry https://registry.npmjs.org    
`which hexo > /dev/null` || npm install -g hexo-cli
```

**Comment by gabrielcsapo** [comment]
I haven't been able to spend much time on maintenance as I don't use local-npm as a main service anymore. 

My thoughts on the current state.
  - heavy (lots of overhead with pouchdb)
  - not really an npm server replacement (which stinks) because it would be great to have a 1:1 API with the official NPM one, but there is no standard API and it seems private (it has a "public" API "documented" https://github.com/npm/registry)
   - no clear purpose with the release of npm@5. (with this release, packages are stored globally and don't reinstall if A. you don't have internet or B. you already have the package reinstalled.

What do you think @MichaelJCole? Thoughts on the future of the project?

**Comment by MichaelJCole** [comment]
Yeah, that's cool about npm 5.

Local-npm was awesome for me when I was travelling and didn't want to
redownload over mobile.  Saved me tons of trouble.

Yeah, maybe it's time has passed w/ npm 5.  There are still a ton of npm <
5 projects out there.  Is there a way to detect npm 5 requests and do a
passthrough?

Otherwise maybe a note in the readme?  I'm not travelling like I used to,
so can turn it off now.

Thanks for this project Gabriel - super cool!

On Mar 9, 2018 10:17 PM, "Gabriel Csapo" <notifications@github.com> wrote:

I haven't been able to spend much time on maintenance as I don't use
local-npm as a main service anymore.

My thoughts on the current state.

   - heavy (lots of overhead with pouchdb)
   - not really an npm server replacement (which stinks) because it would
   be great to have a 1:1 API with the official NPM one, but there is no
   standard API and it seems private (it has a "public" API "documented"
   https://github.com/npm/registry <https://github.com/npm/registry>)
   - no clear purpose with the release of npm@5. (with this release,
   packages are stored globally and don't reinstall if A. you don't have
   internet or B. you already have the package reinstalled.

What do you think @MichaelJCole <https://github.com/michaeljcole>? Thoughts
on the future of the project?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/local-npm/local-npm/issues/169#issuecomment-372006648>,
or mute the thread

**Comment by gabrielcsapo** [comment]
Yeah it is an interesting sort of intersection between something that was so integral that has now been integrated into the package manager. 

I think it has a place in the world especially when it comes to building communities that have a copy of the registry. My thought upon taking on the project was simply to provide a mechanism that lets a user set up a cluster of these in their work, in their house, in their community which could be leveraged by others to take stress off of NPM. 

There are ways that NPM can do this for the community by providing a read/cache only service that users can use, but their primary source of revenue is private repos and showing off how many package  requests they can service every minute/hour/day/week. 

I think if there are enough people using this, it mandates a rewrite and a slimming down of the overall bloat that it provides. For example, there was a constant pull from the public registry, which is not necessary because more than 99% of that metadata is useless. 

Anyone else using local-npm and interested in a smaller footprint server?

**Comment by bluesockets** [comment]
👍

**Comment by gabrielcsapo** [comment]
npm@3 introduced the ability to install while offline. I have talked about this for awhile having a local copy of npm would be super awesome for communities that don't have access to high speed internet or want to have redundancies with @zkat @seldo. I would love to revamp local-npm to be more efficient and maybe even be something baked into npm.

```
npm --share-lan-cache
```

**Comment by zkat** [comment]
P2P stuff is a thing I've thought about, but it probably wouldn't be implemented the way you're suggesting because reasons.

**Comment by gabrielcsapo** [comment]
I saw some interesting chatter about web torrents stuffz in npm. @zkat

**Comment by zkat** [comment]
yeah well don't hold your breath, but there's a way of implementing this I've got in my back pocket to eventually implement as part of a much much bigger-deal change.

**Comment by gabrielcsapo** [comment]
@bluesockets @MichaelJCole do you have an idea of what direction this project should go in?

**Comment by miroamarillo** [comment]
works with node v.8.12.0

**Comment by gabrielcsapo** [comment]
2019 and people are still using local-npm. It makes sense that we keep supporting new versions of node and hopefully I can onboard some more people to help out with modernizing and moving this project forward. Going to close this out and anyone interested in being onboarded as an owner send a DM.
